---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/real estate table/real estate table.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/3/articles/202471/master/file/figures/real%20estate%20table/real%20estate%20table.xlsx"
